### ISSUE TITLE
Not clear how to get generate "application card" or get GENI_KEY from geni website

### ISSUE THREAD

**Issue by davidrpmorris** [Thimxx/pyGenealogical-Tools#126]
I'm missing something and can't figure out how to get started by generating the application card from Geni.com. From the Readme:

> In order to use the interface, you will need to generate an application card inside Geni and obtain a key. You can create the application card in this: location https://www.geni.com/platform/developer/api_explorer

The link opens an API explorer GUI but it's unclear how to generate the key. Couldn't find anything in the Geni API docs either.

Thanks in advance.

**Comment by davidrpmorris** [comment]
Oops - clicking on Applications and starting a new application gets you a token.

Consider linking to: [](https://www.geni.com/platform/developer/apps ) as well in the Readme?

**Comment by Thimxx** [comment]
What would you suggest to avoid the same issue? You meant Readme, but, it will be more sensible to add it in the wiki, isn't it? I would like to not overload the Readme file.
