### ISSUE TITLE
Improve the input parser

### ISSUE THREAD

**Issue by Thimxx** [Thimxx/pyGenealogical-Tools#2]
For the moment I made it old style, Needs to be improved using better tools like yag

**Comment by Matan1988** [comment]
Hey Thimxx, can you please explain my how to use this software? 

When I am trying to run the programme I get this error: FileNotFoundError: [Errno 2] No such file or directory: 'INPUT'

**Comment by Thimxx** [comment]
You are trying to use the 

> Hey Thimxx, can you please explain me how to use this software?
> 
> When I am trying to run the programme I get this error: FileNotFoundError: [Errno 2] No such file or directory: 'INPUT'

You are trying to use an old part of the code, and is giving you an error as the input file is not provided... honestly that part of the code is quite old and now I am targetting to use it more as library to be downloaded by pip here: https://pypi.org/project/pyGenealogicalTools/

If you want to start using it, I can help you directly, just given me your email and we can chat outside Github.

I am quite interested that, any time you find a bug or an issue, you tell me, so I can improve the software based on user feedback

**Comment by Matan1988** [comment]
Hey Timxx, that would be awesome.

My email is: matanran1 @gmail.com

בתאריך יום ה׳, 17 באוק׳ 2019 ב-16:01 מאת Thimxx <notifications@github.com>:

**Comment by Matan1988** [comment]
Of course without a space after the name, so:

Matanran1@gmail.com

בתאריך יום ה׳, 17 באוק׳ 2019 ב-16:57 מאת מתן רן <matanran1@gmail.com>:
